#!/usr/bin/env python3
"""Patch Telegram/BUILD so the Bazel-generated Info.plists clear two validator
warnings that silently block TestFlight install, plus force `get-task-allow=false`
in the entitlements file so Ad Hoc OTA install actually works on registered UDIDs.

Why this file and not the standalone .plist files?
Telegram-iOS' main app and SiriIntents extension Info.plists are NOT shipped as
static .plist files at build time — they are generated by Bazel from inline
`plist_fragment(template = \"\"\"…\"\"\")` blocks inside Telegram/BUILD.
Patching the static Info.plist files therefore has no effect on the compiled
IPA. We have to edit the BUILD templates themselves.

Three edits:

1. TelegramInfoPlist template
   Insert `NSLocationAlwaysAndWhenInUseUsageDescription` right after
   `NSLocationWhenInUseUsageDescription`. Apple validator 90683 warns when
   this key is missing, and iOS silently refuses TestFlight installation with
   "The requested app is not available or does not exist."

2. IntentsInfoPlist template
   Replace the `IntentsSupported` array's body with nothing, so the SiriIntents
   extension declares zero supported intents. This suppresses all validator
   90626 warnings ("No example phrase was provided for INxxxIntent in <lang>")
   that fire for every (intent × locale) pair without a phrase translation —
   dozens of warnings per build. SiriKit then declines to route intents to the
   extension, which is fine: nothing in this project relies on Siri voice
   invocation.

3. TelegramEntitlements template
   Inject `<key>get-task-allow</key><false/>` into the entitlements XML.
   Why: rules_apple's signing logic infers `get-task-allow` from the
   provisioning profile when the entitlements file does not specify it —
   and crucially, it sets `true` whenever the profile has `ProvisionedDevices`
   (i.e. for every Ad Hoc profile), even when the profile's own entitlements
   say `false`. The resulting binary signature mismatches the embedded
   profile's `get-task-allow=false`, and iOS rejects the OTA install at 99.9%
   with "TranslateGram cannot be installed". Specifying the value explicitly
   in the entitlements file overrides the heuristic — codesign uses what's in
   the file. App Store profiles have no ProvisionedDevices so this didn't
   surface for the TestFlight workflow.
"""
import re
import sys


NEW_LOCATION_KEY_BLOCK = """    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>When you send your location to your friends, Telegram needs access to show them a map. You also need this to send locations from an Apple Watch.</string>
"""


def patch_build_file(filepath: str) -> None:
    with open(filepath, "r") as f:
        content = f.read()

    # --- 1. Insert NSLocationAlwaysAndWhenInUseUsageDescription ---
    if "NSLocationAlwaysAndWhenInUseUsageDescription" in content:
        print("  ♻  NSLocationAlwaysAndWhenInUseUsageDescription already present")
    else:
        # Anchor: the two-line block for NSLocationWhenInUseUsageDescription's value.
        # We insert the new key+string AFTER that block.
        anchor = re.search(
            r"(    <key>NSLocationWhenInUseUsageDescription</key>\n    <string>[^<]*</string>\n)",
            content,
        )
        if not anchor:
            print("  ✗  FATAL: anchor NSLocationWhenInUseUsageDescription not found")
            sys.exit(1)
        content = content.replace(anchor.group(0), anchor.group(0) + NEW_LOCATION_KEY_BLOCK, 1)
        print("  ✓  Inserted NSLocationAlwaysAndWhenInUseUsageDescription")

    # --- 2. Empty EVERY IntentsSupported array body ---
    # Telegram/BUILD has three plist_fragment blocks that declare
    # IntentsSupported (Share, IntentsExtension, NotificationService). Only
    # the IntentsExtension one triggers 90626 today because it lists 7 intents,
    # but we empty all three defensively so any future intent addition won't
    # re-introduce missing-phrase warnings.
    pattern = re.compile(
        r"(<key>IntentsSupported</key>\s*\n\s*)<array>(?:\s|<string>[^<]*</string>)*</array>"
    )
    count = 0
    def _empty(m):
        nonlocal count
        count += 1
        return m.group(1) + "<array/>"
    content = pattern.sub(_empty, content)
    if count == 0:
        # Either the file has no IntentsSupported at all, or every block is
        # already empty (`<array/>`). Distinguish the two for a useful log.
        if re.search(r"<key>IntentsSupported</key>\s*\n\s*<array/>", content):
            print("  ♻  IntentsSupported already empty everywhere")
        else:
            print("  ✗  FATAL: no IntentsSupported anchors found")
            sys.exit(1)
    else:
        print(f"  ✓  Emptied {count} IntentsSupported array(s)")

    # --- 3. Force get-task-allow=false into the TelegramEntitlements fragment ---
    if 'get-task-allow' in content:
        print("  ♻  get-task-allow already present in entitlements fragment")
    else:
        # Anchor on the exact opening of the TelegramEntitlements plist_fragment's
        # template list. We prepend a literal XML string before the existing
        # fragment variables so it sits at the top of the rendered entitlements.
        anchor_re = re.compile(
            r'(plist_fragment\(\s*\n\s*name = "TelegramEntitlements",\s*\n\s*extension = "entitlements",\s*\n\s*template = ""\.join\(\[\s*\n)'
        )
        m = anchor_re.search(content)
        if not m:
            print("  ✗  FATAL: TelegramEntitlements plist_fragment anchor not found")
            sys.exit(1)
        injection = '        "<key>get-task-allow</key>\\n<false/>\\n",\n'
        content = anchor_re.sub(m.group(1) + injection, content, count=1)
        print("  ✓  Injected get-task-allow=false into TelegramEntitlements")

    with open(filepath, "w") as f:
        f.write(content)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <path_to_Telegram/BUILD>")
        sys.exit(1)
    patch_build_file(sys.argv[1])
